### ISSUE TITLE
Migrating a volume moves the files out of 'fcd' into a vms folder

### ISSUE THREAD

**Issue by erSitzt** [vmware-samples/cloud-native-storage-self-service-manager#19]
### Describe the bug

When migrating a container volume ,currently attached to a vm named "k8s-worker1", from **datastore1** to **datastore2** the volume will be placed in a folder on the target datastore named like the vm it is attached to, not in a folder named "fcd" like on the source datastore.

### Reproduction steps

1. Deploy a workload with a vmware csi pvc
2. get fcdid of the volume
3. migrate volume from datastore1 to datastore2
...

### Expected behavior

Files remain in "fcd" folder on the destination datastore as well.

Is this a bug of the cns-manager or is this default behavior of vSphere ?

### Additional context

vCenter
Version:	7.0.3
Build:	20990077

**Comment by gohilankit** [comment]
@erSitzt That's the default behavior in vSphere, and not really a bug.

**Comment by hc2p** [comment]
@gohilankit how can we ensure it's going to the same directory though, in this case `/fcd`? This folder is the default folder for vSphere CSI provisioned block storage.

**Comment by erSitzt** [comment]
@gohilankit 
Default behaviour does not mean its no bug ;)
This seems very inconsistent.. why provision the disk in `/fcd` and attach it to a vm only to move it inside the vms directory afterwards.
Migrating a vm with attached container volume does move the vmdk into the vms folder too.

Whats the purpose of the `/fcd` folder then ?
I read somewhere that FCD means First Class Disk which should mean they are independant of the lifecycle of the vm... which seems to be broken when they get moved and renamed into the vms folder on the storage

But this is not an issue with this tool :)
