### ISSUE TITLE
Implement a tool to identify and remove orphan volumes

### ISSUE THREAD

**Issue by SandeepPissay** [vmware-samples/cloud-native-storage-self-service-manager#2]
_Note: I'm moving this feature request from https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/607 to this repo since CNS Manager will be providing this functionality._

There are a few cases where the vSphere CSI driver creates more than 1 volume in vSphere for a PVC. The unused ones become orphans as they are not used by the Kubernetes cluster. This issue is present in all the drivers shipped so far. A separate issue will be filed to improve the idempotency handling but this issue is filed to build a tool that can identify and remove orphan volumes from vSphere. This is very useful for current customers who are using the existing drivers.

**Comment by gohilankit** [comment]
Orphan volume cleanup functionality was added as part of [v0.2.0 release](https://github.com/vmware-samples/cloud-native-storage-self-service-manager/releases/tag/v0.2.0).
