### ISSUE TITLE
Cluster registration only works for first cluster

### ISSUE THREAD

**Issue by owwweiha** [vmware-samples/cloud-native-storage-self-service-manager#7]
### Describe the bug

Using the cluster registration endpoint, e.g.,
```bash
curl -X 'POST' 'http://cns-manager-IP/1.0.0/registercluster?csiDriverSecretName=vsphere-config-secret&csiDriverSecretNamespace=vmware-system-csi' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'clusterKubeConfigFile=@mykubeconfig' -u "user:pass"
```

only the first cluster works. When trying to add a second cluster with a different kubeconfig (generated with get-kubeconfig.sh with a different name then the first config), you'll get an error:

> {"message":"failed to register the cluster.","error":"Secret \"sv-kubeconfig\" is invalid: data[]: Invalid value: \"\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')"}

When using the exact same kubeconfig and put it directly to the K8s secret in cns-manager namespace (e.g., `k -n cns-manager edit secrets sv-kubeconfig`), everything works and all clusters are listed as registered via `listRegisteredClusters` endpoint.

### Reproduction steps

1. Register first cluster via `registercluster` endpoint
2. Try to register second cluster via `registercluster` endpoint

### Expected behavior

Cluster registration should work for more than one K8s cluster. In addition, the get-kubeconfig.sh script might should have a parameter for the [cluster name and context cluster](https://github.com/vmware-samples/cloud-native-storage-self-service-manager/blob/main/scripts/get-kubeconfig.sh#L138-L141), since it has to be unique.

**Comment by gohilankit** [comment]
@owwweiha @rwlib3 I tried to reproduce the issue but I couldn't. Just to mention, I used different input kubeconfig files with `get-kubeconfig.sh`.
Can you list the exact steps to reproduce the issue? Did you use 2 different files as an input to `get-kubeconfig.sh` in each invocation, or did you use the same input kubeconfig with multiple server and contexts defined?

**Comment by owwweiha** [comment]
This seems to work now, at least the issue no longer appears.
